<?php

namespace App\Contracts;

use App\Rates\Result;

class ScenarioB extends Scenario implements ScenarioInterface
{
    public function getPrice(): Result
    {
        return new Result('price', 'distance');
    }

    public function modify(array $modifiers = []): void
    {
        parent::modify($modifiers); // TODO: Change the autogenerated stub
    }
}